version: 2
jobs:
  build-from-source:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          command: |
            go build -o glint
            ./glint examples/main.go
workflows:
  version: 2
  test_code:
    jobs:
      - build-from-source